services:
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - flask
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge